version: '3.8'
services: 
  api:
    build: .
    restart: always 
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
    ports:
      - "6002:6002"
    expose:
      - "6002"
    depends_on:
      - database
    links:
      - database

  database:
    container_name: stac-db
    image: ghcr.io/stac-utils/pgstac:v0.6.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5433:5432"
    command: postgres -N 500