version: '3.8'
services: 
  api:
    build: "."
    restart: always 
    env_file:
      - .env
    ports:
      - "6000:6000"
    expose:
      - "6001"
    depends_on:
      - database
    links:
      - database

  database:
    container_name: stac-db
    image: ghcr.io/stac-utils/pgstac:v0.6.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5432:5432"
    command: postgres -N 500