name: Test goapistac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Test Go application
      run: |
        go test -v ./...
