name: Test goapistac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ghcr.io/stac-utils/pgstac:v0.6.6
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgis
          POSTGRES_USER: username
          PGUSER: username
          PGPASSWORD: password
          PGHOST: localhost
          PGDATABASE: postgis

        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        env:
          discovery.type: single-node
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          xpack.security.enabled: false
        ports:
          - "9200:9200"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Test Go application
        run: |
          go install github.com/joho/godotenv/cmd/godotenv@latest
          echo "$GITHUB_WORKSPACE/go/bin" >> $GITHUB_PATH
          cd pg-api
          godotenv -f .env-example go test ./...
  