name: Test goapistac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create environment file
      run: |
        echo POSTGRES_USER=${{ env.POSTGRES_USE }} > .env
        echo POSTGRES_PASS=${{ env.POSTGRES_PASS }} > .env
        echo POSTGRES_DBNAME=${{ env.POSTGRES_DBNAME }} > .env
        echo POSTGRES_HOST=${{ env.POSTGRES_HOST }} > .env
        echo POSTGRES_PORT=${{ env.POSTGRES_PORT }} > .env

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Test Go application
      run: |
        godotenv -f .env-example go test ./...

    - name: Stop services with Docker Compose
      run: docker-compose down